server:
  port: 8091

spring:
  application:
    name: sharding-service
  
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 10s
  
  # ShardingSphere 配置（单库分表）
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
